"""Assemble the single-file handbook from the chapter files.

Usage: python build_handbook.py
Writes FDE_Handbook.md next to the chapters with a generated table of contents.
Relative links between chapters are rewritten to in-document anchors where the
target is a chapter file; other links are left unchanged.
"""
import pathlib
import re

HERE = pathlib.Path(__file__).parent
ORDER = ["00-Front-Matter.md"] + [
    p.name for p in sorted(HERE.glob("[0-9][0-9]-*.md")) if not p.name.startswith("00-")
] + ["A-Formula-Sheet.md", "B-Sizing-Tables.md", "C-Glossary.md", "D-Bibliography.md"]


def anchor(title):
    a = title.strip().lower()
    a = re.sub(r"[^\w\s-]", "", a)
    return re.sub(r"\s+", "-", a)


def main():
    parts = []
    toc = ["# The Forward Deployed AI Engineer Handbook", "", "Single-file build. Generated by build_handbook.py; edit the chapter files, not this file.", "", "## Contents", ""]
    names = {n: None for n in ORDER}
    for name in ORDER:
        p = HERE / name
        if not p.exists():
            print("missing:", name)
            continue
        text = p.read_text(encoding="utf-8")
        m = re.search(r"^# (.+)$", text, flags=re.M)
        title = m.group(1).strip() if m else name
        names[name] = title
        toc.append(f"- [{title}](#{anchor(title)})")
    for name in ORDER:
        p = HERE / name
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        # rewrite links to sibling chapter files into in-document anchors
        def repl(mm):
            target = mm.group(2)
            base = target.split("#")[0]
            if base in names and names[base]:
                return f"[{mm.group(1)}](#{anchor(names[base])})"
            return mm.group(0)
        text = re.sub(r"\[([^\]]+)\]\(([^)\s]+\.md(?:#[^)]*)?)\)", repl, text)
        parts.append(text.rstrip() + "\n\n---\n")
    out = "\n".join(toc) + "\n\n---\n\n" + "\n".join(parts)
    (HERE / "FDE_Handbook.md").write_text(out, encoding="utf-8")
    print("wrote FDE_Handbook.md:", out.count("\n") + 1, "lines,", len(out) // 1024, "KB")


if __name__ == "__main__":
    main()
